### ISSUE TITLE
Refractor the Router

### ISSUE THREAD

**Issue by manzil-infinity180** [juninhokaponne/friendRecomendation#1]
Example - Move this to controller file with specific file and then exports from the controller 
(req, res) => {
  const { cpf, name } = req.body;
  const result = personController.createPerson(cpf, name);
  res.status(result.error ? 400 : 200).send(result);
}

**Comment by juninhokaponne** [comment]
Hey Manzil, Nice one, It's a good way to do that, I refactored the Person routes. 

If you feel comfortable contributing to this project, I can assign for you a new issue to refactor the relationshipController.js!

About the point of this issue, below is the simple modification in routes.js file and some modifications in PersonController.js.

You can see PR link [Here 🚀 ](https://github.com/juninhokaponne/friendRecomendation/compare/dev?expand=1)

## Before

![carbon (1)](https://github.com/juninhokaponne/friendRecomendation/assets/49099875/c4e1139e-9dd6-4fc6-8a89-2d0d3b1b833a)

## Current
![carbon](https://github.com/juninhokaponne/friendRecomendation/assets/49099875/61d0ad3d-7430-4b54-955f-71efcc921e43)

Thank you for collaborating, feel free to contribute to the project with ideas, bugs or Pull requests.

**Comment by manzil-infinity180** [comment]
> Hey Manzil, Nice one, It's a good way to do that, I refactored the Person routes.
> 
> If you feel comfortable contributing to this project, I can assign for you a new issue to refactor the relationshipController.js!
> 
> About the point of this issue, below is the simple modification in routes.js file and some modifications in PersonController.js.
> 
> You can see PR link [Here 🚀 ](https://github.com/juninhokaponne/friendRecomendation/compare/dev?expand=1)
> 
> ## Before
> ![carbon (1)](https://user-images.githubusercontent.com/49099875/270518348-c4e1139e-9dd6-4fc6-8a89-2d0d3b1b833a.png)
> 
> ## Current
> ![carbon](https://user-images.githubusercontent.com/49099875/270518228-61d0ad3d-7430-4b54-955f-71efcc921e43.png)
> 
> Thank you for collaborating, feel free to contribute to the project with ideas, bugs or Pull requests.

Sure , i am ready with my PR (assign to me)

**Comment by manzil-infinity180** [comment]
#3

**Comment by juninhokaponne** [comment]
Your changes have been merged and can now be seen in the main branch 🥇.

Thank you for your contribution, feel free to continue working to improve the project.
