### ISSUE TITLE
Developing the landing page

### ISSUE THREAD

**Issue by sanchitaa14** [juninhokaponne/friendRecomendation#4]
Hey, I would love to contribute to this project and develop a landing page with proper info on how to proceed for the same.

**Comment by juninhokaponne** [comment]
Hey, that's good to hear.

If you are really interested in doing this, feel free to contribute to the project.

You can start forking this project and then send me the PR for review and if it's ok to merge with the main branch.

Tell me more about your idea, is it like a documentation page or something like that ?

**Comment by sanchitaa14** [comment]
Well, firstly to get people to use your algo through a website the landing page should be catchy, so when the site is opened i am planning to make the theme simple and elegant with a brief on what exactly the algo does, and when the user scrolls down they can put their names to check the relationship between the users or something like that, rest you can tell me how you want it to be.

**Comment by juninhokaponne** [comment]
Great, I advise you to start by developing the landing page with the possibility at first that the user can view the relationship and recommendation of friends who already exist in the code.

This way he will understand the algorithm and later we can do something more dynamic where a random user can be recommended to another as a friend.

Feel free to start development, you can link the landing page in the documentation and we will later post it on Vercel to make the view available to everyone.

**Comment by sanchitaa14** [comment]
Sure I'll work on it and post a pr after 1st oct, when hacktober starts if thats okay

**Comment by juninhokaponne** [comment]
Okay, perfect, after you finish your PR I will attach your PR to this issue if everything is right and then mark it as closed.

**Comment by juninhokaponne** [comment]
Hey @sanchitaa14.
Are you working on this issue ? if isn't working on this issue I'll closed this issue.

**Comment by sanchitaa14** [comment]
Yeah, I'm working on it, I'll submit my pr in two days time for sure.

**Comment by juninhokaponne** [comment]
Okay, don't worry, it's just for control. After your PR and a few others, I will send a new release with all these features. Thanks

**Comment by sanchitaa14** [comment]
So I did make the landing page but I am having a hard time connecting the backend with it

**Comment by juninhokaponne** [comment]
What are your difficulties? Maybe I can help you with that.

**Comment by sanchitaa14** [comment]
I am unable to show the actual result on screen that comes at the end of the algorithm.

**Comment by juninhokaponne** [comment]
Don't worry, you can submit a PR as is and then we will contribute to this landing page.
