### ISSUE TITLE
[Feature] [hacktoberfest] Get all(person or realtionship) on one go just like we are getting the person via 'GET /person/:CPF'

### ISSUE THREAD

**Issue by manzil-infinity180** [juninhokaponne/friendRecomendation#5]
confused to do so , sir please help me , how i can acheive that things

**Comment by juninhokaponne** [comment]
The requirements of the document found in the documentation required the division of functionalities, thus separating Get user relationship and another to get only the person using the CPF (identification document).
I don't know if it would be good to do this in just one feature, can you give me more details and an example?

**Comment by manzil-infinity180** [comment]
> The requirements of the document found in the documentation required the division of functionalities, thus separating Get user relationship and another to get only the person using the CPF (identification document). I don't know if it would be good to do this in just one feature, can you give me more details and an example?

Like using mongodb we use - UserSchema.find() to get all data related to that schema like this we can get all person detail (something like this)

**Comment by juninhokaponne** [comment]
Got it, it looks interesting, do you want to implement this? But just make sure the tests don't get interrupted. If you need help, you can contact me.

If you agree to do it, I'll do a review after that.

**Comment by manzil-infinity180** [comment]
> Got it, it looks interesting, do you want to implement this? But just make sure the tests don't get interrupted. If you need help, you can contact me.
> 
> If you agree to do it, I'll do a review after that.

Sir it looks difficult to me , help me by how i can achieve this

**Comment by juninhokaponne** [comment]
Of course, first let me make sure I understand your question correctly, you want to create a new route of type getAll(person or realtionship) and for this you exemplified using mongo UserSchema.find().
Is this your main doubt?

**Comment by juninhokaponne** [comment]
I'll closed this issue and you can send your questions, comments, improvements and more here on your another issue that's assigned for you.
https://github.com/juninhokaponne/friendRecomendation/issues/6
